### ISSUE TITLE
Allow burnerwallet to connect to any dApp using WalletConnect

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/burnerwallet#17]
As Punk Wallet does, we want to be able to scan a Wallet Connect QR in any given dApp, and connect to it.

We can check how it's implemented there.

Workflow:
1. Scan WalletConnect QR
2. BurnerWallet is connected to dApp (maybe show it somewhere)
3. We send a TX in the dApp
4. Burner Wallet gets prompted with a screen to confirm (with tx data)
5. Ability to disconnect from the dApp?

This might be a lot of stuff, we can split in different PRs.

**Comment by damianmarti** [comment]
Closing this issue. 

WalletConnect implemented #46 

Pending issues #60
