### ISSUE TITLE
Send screen

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/burnerwallet#39]
I think the send screen could use a bit more love:

![image](https://github.com/BuidlGuidl/burnerwallet/assets/2486142/aa7675fc-cc63-4d66-b6fa-89b813d725b4)

Some suggestions:

- Better inputs in general
- It seems a bit squished down, could use some more vertical height (maybe higher inputs, more space..)
   - Maybe we need to tweak the default SE-2 components.
-  allow ETH / USD conversion on the amount of input (we have a input that does that on SE-2)

I think @ChangoMan might have a good hand for this. (we can always ask Andrea too!)

We can also tackle this in separate PRs.

(No rush on this)

**Comment by ChangoMan** [comment]
Taking a crack at this via https://github.com/BuidlGuidl/burnerwallet/pull/41

Maybe a little better but I am open to another set of designer eyes and suggestions!

**Comment by carletex** [comment]
Amazing stuff!

I think we can close this. I'll move "allow ETH / USD conversion on the amount of input (we have a input that does that on SE-2)" to another issue.
