### ISSUE TITLE
History does not show transactions received while you have it open

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/burnerwallet#54]
Balance gets refreshed when you receive ETH with the burner wallet open, but History does not refresh until you refresh burner.

Might be related with https://github.com/BuidlGuidl/burnerwallet/issues/48

**Comment by ChangoMan** [comment]
This is because we don't have a polling on fetching the history data. We could add that and the history would update regularly. Do we know how often we might want to re-fetch the history data? Maybe every 1 minute, or is that too often?

**Comment by carletex** [comment]
> Do we know how often we might want to re-fetch the history data? Maybe every 1 minute, or is that too often?

We could use `pollingInterval` from `scaffold.config.ts` (defaults to 30s). 

Ideally, I guess we only want to make those requests when the "tab" is active. Maybe this is already the default in browsers?

**Comment by Pabl0cks** [comment]
Merged yesterday!
